# This is a basic workflow to help you get started with Actions
name: AndroidCICDBuild

# Controls when the workflow will run
on:
  # Triggers the workflow on pull or push request events but only for the "main" branch
  pull_request :
    branches : [ master ]
  push :
    branches : [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on : ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name : Checkout
        uses: actions/checkout@v4.1.1

      # Set Up Java JDK
      - name: Setup Java JDK
        uses: actions/setup-java@v4.0.0
        with:
          java-version: '18'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      # Build with Gradle
      - name : Build with Gradle
        run : ./gradlew build


      # Build APK from given path
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v4.0.0
        with:
          name: AndroidCICD.apk
          path: app/build/outputs/apk/debug/app-debug.apk

      # Sending Push message in Slack
      - name: Send GitHub Action trigger data to Slack workflow
        id: slack
        uses: mariobodemann/slack@v0.0.3
        with:
          status: ${{ job.status }}
          message: 'Push update in Slack from master branch'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      # Send APK on slack
      - uses: MeilCli/slack-upload-file@v3.1.3
        with:
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
          file_path: app/build/outputs/apk/debug/app-debug.apk
          title: 'Android CICD APK'
          initial_comment: 'New build available now.'